apiVersion: v1
kind: ConfigMap
metadata:
  name: blue-team-config
  namespace: voting-system

data:
  TEAM_NAME: "Blue Team"
  BG_HEX: "#1a237e"
  ACCENT_HEX: "#42a5f5"

  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"

  VOTE_KEY: "blue_votes"
